config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Simple Airbnb</a>
    <div class="d-flex justify-content-end">
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success me-2" type="submit">Search</button>
      </form>
      <button class="btn btn-outline-primary" type="button">Add Flat</button>
    </div>
  </div>
</nav>

app/views/flats/index.html.erb
<div>
  <h1>All our Flats</h1>
  <p>All <%= @flats.count %> flats.</p>
</div>
<div class="cards">
  <% @flats.each do |flat| %>
    <div class="card">
      <img src="https://woodboom.de/cdn/shop/products/Eichenbett-Massivholz-schwebend_3_5b602874-dcae-42ff-8d5e-0a73314b97f6.jpg?v=1629705582" class="card-img-top" alt="...">
      <div class="card-body bg-light">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text">
          <%= flat.address %> <br>
          <i class="fa-solid fa-euro-sign"></i><%= flat.price_per_night %> <%= flat.number_of_guests %>
        </p>
      </div>
      <div class="card-footer bg-white">
        <%= link_to "More info", flat_path(flat) %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "flats/navbar" %>
      <div class="container">
    <%= yield %>
    </div>
  </body>
</html>